# Generated by Django 5.1.7 on 2025-03-17 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_name', models.CharField(max_length=256)),
                ('status_code', models.IntegerField()),
                ('message', models.TextField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('request_token', models.CharField(blank=True, max_length=64, null=True)),
                ('request_user_agent', models.TextField(blank=True, null=True)),
                ('request_ipv4', models.TextField()),
                ('request_url', models.TextField(blank=True, null=True)),
                ('request_controller', models.TextField(blank=True, null=True)),
                ('request_action', models.TextField(blank=True, null=True)),
                ('request_id', models.TextField(blank=True, null=True)),
                ('request_body', models.BinaryField(blank=True, null=True)),
                ('request_body_content_type', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhraseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_translation', to=settings.AUTH_USER_MODEL)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.phrase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
