# Generated by Django 5.1.7 on 2025-03-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasetranslation',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='translations', to='core.phrase'),
        ),
    ]
