# Generated by Django 5.1.7 on 2025-07-02 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_file_file_hash_file_core_file_file_ha_8fa9b7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='phrasetranslation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
