# Generated by Django 5.1.7 on 2025-07-17 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_phrase_uuid_phrasetranslation_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_controller', models.CharField(max_length=128)),
                ('resource_action', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('nothing_happened', 'Nothing Happened'), ('got_notification', 'User Got Notification'), ('viewed_notification', 'User Viewed Notification'), ('opened_notification', 'User Opened Notification')], default='nothing_happened', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
