# Generated by Django 5.1.7 on 2025-07-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('warning', 'Warning'), ('pending', 'Pending')], default='pending', max_length=16),
        ),
    ]
