# Generated by Django 5.1.7 on 2025-07-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification_description_notification_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message_status',
            new_name='message_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='resource_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
