# Generated by Django 5.1.7 on 2025-03-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mushaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short_name', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.TextField()),
                ('source', models.TextField()),
            ],
        ),
    ]
