# Generated by Django 5.1.7 on 2025-03-23 14:06

from django.db import migrations

import json
import os


def load_quran(apps, schema_editor):
    Mushaf = apps.get_model("quran", "Mushaf")
    Ayah = apps.get_model("quran", "Ayah")
    Word = apps.get_model("quran", "Word")
    # Load quran data file
    with open("./quran.json", "r") as f:
        quran_data = json.load(f)
    mushaf_data = quran_data["mushaf"]

    Mushaf.objects.create(creator_id=1, name=mushaf_data["name"], short_name=mushaf_data["short_name"], source=mushaf_data["source"])

    ayahs = []
    words = []
    
    # TODO: this is insane time complexity O(n^3) 
    for surah_data in quran_data["surahs"]:
        surah = Mushaf.objects.get(name=mushaf_data["name"])\
            .surahs.create(creator_id=1,number=surah_data["number"], name=surah_data["name"], period=surah_data["period"])
        surah.save()
        for ayah in surah_data["ayahs"]:
            ayahs.append(Ayah(
                creator_id=1,
                surah_id=surah_data["number"],
                number=ayah["number"],
                sajdah=ayah["sajdah"],
                is_bismillah=ayah["is_bismillah"],
                bismillah_text=ayah["bismillah_text"],))
            for word in ayah["words"]:
                words.append(Word(ayah_id=ayah["number"], text=word["text"], creator_id=1))

    Ayah.objects.bulk_create(ayahs)
    Word.objects.bulk_create(words)

def load_translations(apps, schema_editor):
    Translation = apps.get_model("quran", "Translation")
    User = apps.get_model("auth", "User")
    AyahTranslation = apps.get_model("quran", "AyahTranslation")

    ayah_translations = []

    # Load translations files
    for translation in list(os.scandir("./translations")):
        with open(translation,"r") as f:
            translation_data = json.load(f)
        user, _ = User.objects.get_or_create(username=translation_data["translator_username"])
        
        translation = Translation.objects.create(
            creator_id=1,
            mushaf_id=1,
            translator_id=user.id,
            source=translation_data["source"],
            approved=True,
            language=translation_data["language"],
        )
        translation.save()
        first_ayah = translation_data["surahs"][0]["ayah_translations"][0]['text']
        for surah in translation_data["surahs"]:
            for ayah in surah["ayah_translations"]:
                ayah_translations.append(AyahTranslation(
                    creator_id=1,
                    translation_id=translation.id,
                    ayah_id=ayah["number"],
                    text=ayah["text"],
                    bismillah=first_ayah,
                ))

    AyahTranslation.objects.bulk_create(ayah_translations)


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_quran, reverse_code=migrations.RunPython.noop,),
        migrations.RunPython(load_translations, reverse_code=migrations.RunPython.noop,),
    ]
