# Generated by Django 5.1.7 on 2025-07-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recitation',
            name='surah',
        ),
    ]
