# Generated by Django 5.1.7 on 2025-03-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mushaf',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
