# Generated by Django 5.1.7 on 2025-07-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recitationtimestamp',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recitationtimestamp',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
