# Generated by Django 5.1.7 on 2025-07-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_remove_recitation_surah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recitation',
            name='file',
        ),
    ]
