# Generated by Django 5.1.7 on 2025-07-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_auto_20250323_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushaf',
            name='short_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
