# Generated by Django 5.1.7 on 2025-03-13 13:37

from django.db import migrations

def add_mushaf(apps, schema_editor):
    Mushaf = apps.get_model("quran", "Mushaf")
    hafs = Mushaf(creator_id= 1, short_name="hafs", name="Hafs", source="https://tanzil.com/")
    hafs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_rename_creator_id_mushaf_creator'),
    ]

    operations = [
        migrations.RunPython(add_mushaf),
    ]
