# Generated by Django 5.1.7 on 2025-06-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_auto_20250323_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='recitation',
            name='surah',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='quran.surah'),
            preserve_default=False,
        ),
    ]
