# Generated by Django 5.1.7 on 2025-05-29 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_auto_20250323_1406'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushaf',
            name='short_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mushaf',
            name='source',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=10)),
                ('size', models.BigIntegerField()),
                ('s3_uuid', models.UUIDField()),
                ('upload_name', models.CharField(max_length=255)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_files', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recitation_date', models.DateField()),
                ('recitation_location', models.TextField()),
                ('duration', models.DurationField()),
                ('recitation_type', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='quran.file')),
                ('mushaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='quran.mushaf')),
                ('reciter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recited_works', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
