# Generated by Django 5.1.7 on 2025-06-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_recitation_surah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='approved',
        ),
        migrations.AddField(
            model_name='mushaf',
            name='status',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recitation',
            name='status',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='status',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
