# Generated by Django 5.1.7 on 2025-05-29 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_file'),
        ('quran', '0003_alter_mushaf_short_name_alter_mushaf_source_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recitation',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='core.file'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
