# Generated by Django 5.1.7 on 2025-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_remove_recitation_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayahbreaker',
            name='name',
        ),
        migrations.AddField(
            model_name='ayahbreaker',
            name='type',
            field=models.CharField(choices=[('page', 'Page'), ('juz', 'Juz'), ('hizb', 'Hizb'), ('rub', 'Rub'), ('manzil', 'Manzil'), ('ruku', 'Ruku')], default='page', max_length=20),
            preserve_default=False,
        ),
    ]
