# Generated by Django 5.1.7 on 2025-07-31 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0004_remove_ayahbreaker_name_ayahbreaker_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Takhtit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takhtit_accounts', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takhtits', to=settings.AUTH_USER_MODEL)),
                ('mushaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takhtits', to='quran.mushaf')),
            ],
        ),
        migrations.AddField(
            model_name='ayahbreaker',
            name='takhtit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ayah_breakers', to='quran.takhtit'),
        ),
    ]
