# Generated by Django 5.1.7 on 2025-05-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0004_alter_recitation_file_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecitationTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitation_timestamps', to='quran.ayah')),
                ('recitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='quran.recitation')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitation_timestamps', to='quran.surah')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
