# Generated by Django 5.1.7 on 2025-07-31 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0005_takhtit_ayahbreaker_takhtit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbreaker',
            name='name',
        ),
        migrations.AddField(
            model_name='wordbreaker',
            name='takhtit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_breakers', to='quran.takhtit'),
        ),
        migrations.AddField(
            model_name='wordbreaker',
            name='type',
            field=models.CharField(choices=[('line', 'Line')], default='line', max_length=20),
        ),
    ]
